### PR TITLE
Language selection

### PR DESCRIPTION
**Pull request by timkarnold**

### CODE REVIEW

**Comment by tevko** [comment]
Can you provide a quick overview of how this works? I tested on your branch and I wasn't seeing the API calls go out with the selected language

**Comment by timkarnold** [comment]
It's using a copy of the "Written in this language" dropdown from [Github Advanced Search](https://github.com/search/advanced) to fill in the [Search API](https://developer.github.com/v3/search/#parameters) `language` parameter.

Looks like if you tested my branch via the README.md link it went back to your production, so you might have not seen the changes. Correct testing link is http://timkarnold.github.io/practice/github.html

**Comment by tevko** [comment]
Maybe I'm misunderstanding, but when I test that URL, I'm opening dev
tools, clicking on the network tab, and looking at the request URL, in
which there are no language parameters
654c184c-0860-11e4-91b7-9630b4c8d05b

**Comment by timkarnold** [comment]
Doh, sorry my commit was missing a key line. Try again now :-)

**Comment by tevko** [comment]
Awesome. Implementing in next release

**Pull request closed without merging**
